//////////////////////////////////////////////////////////////////////////
// Generated by Dockyard, do not edit, manual changes will be overwritten

#include "stdafx.h"
#include "TextureManager.h"

//////////////////////////////////////////////////////////////////////////

namespace hvgs
{

//////////////////////////////////////////////////////////////////////////

void CTextureManager::Init()
{
	for (size_t i = 0; i < size_t(TextureName::COUNT); i++)
	{
		TextureName textureName = TextureName(i);

		std::string fileName;

		switch (textureName)
		{
		case TextureName::BACKGROUND:
			fileName = "..\\Resources\\Textures\\background.png";
			break;
		case TextureName::ACTOR:
			fileName = "..\\Resources\\Textures\\Actor.png";
			break;
		case TextureName::BUTTON_DEFAULT:
			fileName = "..\\Resources\\Textures\\Button\\Default.png";
			break;
		case TextureName::BUTTON_HOVER:
			fileName = "..\\Resources\\Textures\\Button\\Hover.png";
			break;
		case TextureName::BUTTON_DEACTIVATED:
			fileName = "..\\Resources\\Textures\\Button\\Deactivated.png";
			break;
		case TextureName::BUTTON_PRESSED:
			fileName = "..\\Resources\\Textures\\Button\\Pressed.png";
			break;
		case TextureName::TILEATLAS:
			fileName = "..\\Resources\\Textures\\TileAtlas\\Final_Atlas.png";
			break;
		case TextureName::INVENTORYMAINSPRITE:
			fileName = "..\\Resources\\Textures\\Scenes\\InventoryMainSprite.png";
			break;
		case TextureName::ITEM_DIRT:
			fileName = "..\\Resources\\Textures\\TileAtlas\\Dirt.png";
			break;
		case TextureName::ITEM_STONE:
			fileName = "..\\Resources\\Textures\\TileAtlas\\Stone.png";
			break;
		case TextureName::ITEM_IRON:
			fileName = "..\\Resources\\Textures\\TileAtlas\\Iron.png";
			break;
		case TextureName::WHITE:
			fileName = "..\\Resources\\Textures\\TileAtlas\\White.png";
			break;
		case TextureName::BLACK:
			fileName = "..\\Resources\\Textures\\TileAtlas\\Black.png";
			break;
		case TextureName::BUILDING_BROKER:
			fileName = "..\\Resources\\Textures\\Buildings\\Broker.png";
			break;
		case TextureName::SCENEBUILDINGBROKER:
			fileName = "..\\Resources\\Textures\\Scenes\\BrokerUI.png";
			break;
		case TextureName::ACTOR_THRUSTER:
			fileName = "..\\Resources\\Textures\\Actor_Thruster.png";
			break;
		case TextureName::BUTTONICON_XBOX_ONE_A:
			fileName = "D:\\Users\\Thorsten\\Documents\\Graphics\\Platform Buttons\\Xelu_FREE_keyboard&controller_prompts_pack\\Xbox One\\XboxOne_A.png";
			break;
		case TextureName::BUTTONICON_XBOX_ONE_B:
			fileName = "D:\\Users\\Thorsten\\Documents\\Graphics\\Platform Buttons\\Xelu_FREE_keyboard&controller_prompts_pack\\Xbox One\\XboxOne_B.png";
			break;
		case TextureName::BUTTONICON_XBOX_ONE_X:
			fileName = "D:\\Users\\Thorsten\\Documents\\Graphics\\Platform Buttons\\Xelu_FREE_keyboard&controller_prompts_pack\\Xbox One\\XboxOne_X.png";
			break;
		case TextureName::BUTTONICON_XBOX_ONE_Y:
			fileName = "D:\\Users\\Thorsten\\Documents\\Graphics\\Platform Buttons\\Xelu_FREE_keyboard&controller_prompts_pack\\Xbox One\\XboxOne_Y.png";
			break;
		case TextureName::KEYBOARDICON_E:
			fileName = "D:\\Users\\Thorsten\\Documents\\Graphics\\Platform Buttons\\Xelu_FREE_keyboard&controller_prompts_pack\\Keyboard & Mouse\\Light\\Keyboard_White_E.png";
			break;
		case TextureName::BUTTON_SPECIAL_INTERACTION:
			fileName = "..\\Resources\\Textures\\Special Button Sprites\\Interaction.png";
			break;
		case TextureName::BACKGROUND_SPACE:
			fileName = "..\\Resources\\Textures\\background_space.png";
			break;
		case TextureName::COAL:
			fileName = "..\\Resources\\Textures\\TileAtlas\\Coal.png";
			break;

		default:
			break;
		}

		sf::Texture texture;
		if (!texture.loadFromFile(fileName))
		{
			LOG_ERROR("Could not load texture with filename " << fileName);
			continue;
		}

		m_TextureTable.emplace(std::move(textureName), std::move(texture));
	}

}

//////////////////////////////////////////////////////////////////////////

const sf::Texture* CTextureManager::GetTexture(TextureName textureName) const
{
	auto it = m_TextureTable.find(textureName);
	ASSERT_OR_EXECUTE(it != m_TextureTable.end(), return nullptr);
	return &it->second;
}

//////////////////////////////////////////////////////////////////////////

} // hvgs
