#pragma once

namespace hvgs
{

//////////////////////////////////////////////////////////////////////////

enum class TextureName
{
	INVALID = -1,
	BACKGROUND,
	ACTOR,
	BUTTON_DEFAULT,
	BUTTON_HOVER,
	BUTTON_DEACTIVATED,
	BUTTON_PRESSED,
	TILEATLAS,
	INVENTORYMAINSPRITE,
	ITEM_DIRT,
	ITEM_STONE,
	ITEM_IRON,
	WHITE,
	BLACK,
	BUILDING_BROKER,
	SCENEBUILDINGBROKER,
	ACTOR_THRUSTER,
	BUTTONICON_XBOX_ONE_A,
	BUTTONICON_XBOX_ONE_B,
	BUTTONICON_XBOX_ONE_X,
	BUTTONICON_XBOX_ONE_Y,
	KEYBOARDICON_E,
	BUTTON_SPECIAL_INTERACTION,
	BACKGROUND_SPACE,
	COAL,
	FUELTANK,
	BUILDING_WORKSHOP,
	MODULE_TANK_1,
	MODULE_TANK_2,
	MODULE_TANK_3,
	MODULE_TANK_4,
	MODULE_TANK_5,
	MODULE_TANK_6,
	MODULE_TANK_7,
	MODULE_TANK_8,
	MODULE_MOTOR_1,
	MODULE_MOTOR_2,
	MODULE_MOTOR_3,
	MODULE_MOTOR_4,
	MODULE_MOTOR_5,
	MODULE_MOTOR_6,
	MODULE_MOTOR_7,
	MODULE_MOTOR_8,
	BUILDING_WORKSHOP_UI_SELECTION_FRAME,
	BUILDING_WORKSHOP_UI_SELECTION_FRAME_HOVER,
	BUILDING_WORKSHOP_UI_SELECTION_FRAME_PRESSED,
	BUILDING_WORKSHOP_UI_CLOSE_BUTTON,
	COUNT

};

//////////////////////////////////////////////////////////////////////////

}